version: 1.0.{build}
build:
  verbosity: minimal

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

